export const GET_SERVER_CLASSIFY = 'GET_SERVER_CLASSIFY'
export const UPLOAD_File = 'UPLOAD_File'
export const SET_File = 'SET_File'
export const SAVE_File = 'SAVE_File'
export const SET_PIC = 'SET_PIC'
