// export const INPUT_USERNAME = 'INPUT_USERNAME'
// export const INPUT_PASSWORD = 'INPUT_PASSWORD'
// export const SUBMIT_IT = 'SUBMIT_IT'
// export const SUBMIT_LOGIN = 'SUBMIT_LOGIN'
// export const SUBMIT_REGISTER = 'SUBMIT_REGISTER'